/**
 * @file Post.hpp
 * @brief Post domain model. Generated by scripts/new-resource.sh.
 *
 * Add your real columns below — keep the struct, from_row() and to_json()
 * in sync (each field appears in all three). Never serialize secrets in
 * to_json (see tests/unit/test_domain_serialization.cpp).
 */

#pragma once

#include <optional>
#include <pqxx/pqxx>
#include <string>
#include <vector>

#include <nlohmann/json.hpp>

#include "utils/Time.hpp"

namespace Domain {

// Tags travel between the DB and the domain as one comma-joined TEXT column
// (tags are constrained keywords with no commas — see migration 007). These two
// helpers are the single split/join boundary; keep them a pair.
inline std::vector<std::string> split_tags(const std::string& csv) {
    std::vector<std::string> out;
    std::size_t start = 0;
    while (start <= csv.size()) {
        std::size_t comma = csv.find(',', start);
        std::string t = csv.substr(start, comma == std::string::npos ? std::string::npos : comma - start);
        // Trim surrounding whitespace; drop empties (handles "" and trailing commas).
        std::size_t b = t.find_first_not_of(" \t");
        std::size_t e = t.find_last_not_of(" \t");
        if (b != std::string::npos)
            out.push_back(t.substr(b, e - b + 1));
        if (comma == std::string::npos)
            break;
        start = comma + 1;
    }
    return out;
}

inline std::string join_tags(const std::vector<std::string>& tags) {
    std::string out;
    for (const auto& t : tags) {
        if (!out.empty())
            out += ',';
        out += t;
    }
    return out;
}

struct Post {
    std::string id;    // UUID v4 (text)
    std::string slug;  // URL key
    std::string title;
    std::string summary;            // list/teaser blurb
    std::string body;               // Markdown source
    std::string status;             // draft | published
    std::string topic;              // section label (e.g. "Kubernetes")
    std::vector<std::string> tags;  // keyword tags (drive the index tag cloud)
    std::optional<std::string> published_at;
    std::string created_at;
    std::string updated_at;

    template <typename Row>
    static Post from_row(const Row& row) {
        Post e;
        e.id = row["id"].template as<std::string>();
        e.slug = row["slug"].template as<std::string>();
        e.title = row["title"].template as<std::string>();
        e.summary = row["summary"].template as<std::string>();
        e.body = row["body"].template as<std::string>();
        e.status = row["status"].template as<std::string>();
        e.topic = row["topic"].template as<std::string>();
        e.tags = split_tags(row["tags"].template as<std::string>());
        // API-facing timestamps are ISO 8601 UTC; libpqxx hands us Postgres
        // text form ("YYYY-MM-DD HH:MM:SS.ffffff+00") — convert at this single
        // DB→domain boundary so every serializer downstream inherits it.
        if (!row["published_at"].is_null())
            e.published_at = Utils::Time::pg_to_iso8601(row["published_at"].template as<std::string>());
        e.created_at = Utils::Time::pg_to_iso8601(row["created_at"].template as<std::string>());
        e.updated_at = Utils::Time::pg_to_iso8601(row["updated_at"].template as<std::string>());
        return e;
    }
};

inline void to_json(nlohmann::json& j, const Post& e) {
    j = nlohmann::json{
        {"id", e.id},
        {"slug", e.slug},
        {"title", e.title},
        {"summary", e.summary},
        {"body", e.body},
        {"status", e.status},
        {"topic", e.topic},
        {"tags", e.tags},
        {"published_at", e.published_at ? nlohmann::json(*e.published_at) : nlohmann::json(nullptr)},
        {"created_at", e.created_at},
        {"updated_at", e.updated_at},
    };
}

// Lightweight list projection for the public index: everything a post card
// needs (never the full Markdown body). read_mins is computed in SQL from the
// body's word count, so the index can show reading time without shipping bodies
// — the whole feed is one small payload. Full body comes from the by-slug read.
struct PostCard {
    std::string slug;
    std::string title;
    std::string summary;
    std::string topic;
    std::vector<std::string> tags;
    std::optional<std::string> published_at;
    int read_mins = 1;

    template <typename Row>
    static PostCard from_row(const Row& row) {
        PostCard c;
        c.slug = row["slug"].template as<std::string>();
        c.title = row["title"].template as<std::string>();
        c.summary = row["summary"].template as<std::string>();
        c.topic = row["topic"].template as<std::string>();
        c.tags = split_tags(row["tags"].template as<std::string>());
        if (!row["published_at"].is_null())
            c.published_at = Utils::Time::pg_to_iso8601(row["published_at"].template as<std::string>());
        c.read_mins = row["read_mins"].template as<int>();
        return c;
    }
};

inline void to_json(nlohmann::json& j, const PostCard& c) {
    j = nlohmann::json{
        {"slug", c.slug},
        {"title", c.title},
        {"summary", c.summary},
        {"topic", c.topic},
        {"tags", c.tags},
        {"published_at", c.published_at ? nlohmann::json(*c.published_at) : nlohmann::json(nullptr)},
        {"read_mins", c.read_mins},
    };
}

}  // namespace Domain
