/**
 * @file Post.hpp
 * @brief Post domain model. Generated by scripts/new-resource.sh.
 *
 * Add your real columns below — keep the struct, from_row() and to_json()
 * in sync (each field appears in all three). Never serialize secrets in
 * to_json (see tests/unit/test_domain_serialization.cpp).
 */

#pragma once

#include <optional>
#include <pqxx/pqxx>
#include <string>

#include <nlohmann/json.hpp>

namespace Domain {

struct Post {
    std::string id;    // UUID v4 (text)
    std::string slug;  // URL key
    std::string title;
    std::string summary;  // list/teaser blurb
    std::string body;     // Markdown source
    std::string status;   // draft | published
    std::optional<std::string> published_at;
    std::string created_at;
    std::string updated_at;

    template <typename Row>
    static Post from_row(const Row& row) {
        Post e;
        e.id = row["id"].template as<std::string>();
        e.slug = row["slug"].template as<std::string>();
        e.title = row["title"].template as<std::string>();
        e.summary = row["summary"].template as<std::string>();
        e.body = row["body"].template as<std::string>();
        e.status = row["status"].template as<std::string>();
        if (!row["published_at"].is_null())
            e.published_at = row["published_at"].template as<std::string>();
        e.created_at = row["created_at"].template as<std::string>();
        e.updated_at = row["updated_at"].template as<std::string>();
        return e;
    }
};

inline void to_json(nlohmann::json& j, const Post& e) {
    j = nlohmann::json{
        {"id", e.id},
        {"slug", e.slug},
        {"title", e.title},
        {"summary", e.summary},
        {"body", e.body},
        {"status", e.status},
        {"published_at", e.published_at ? nlohmann::json(*e.published_at) : nlohmann::json(nullptr)},
        {"created_at", e.created_at},
        {"updated_at", e.updated_at},
    };
}

}  // namespace Domain
