/**
 * @file test_post.cpp
 * @brief Integration tests for PostsController. Generated by new-resource.sh.
 *        Fill in once the migration + real columns exist.
 *
 * NB: this file lives in tests/integration/, so CMake's CONFIGURE_DEPENDS glob
 * compiles it automatically — there is no bucket list to register it in. It
 * needs a 'posts' table (the co-generated migration creates the stub).
 */

#include <gtest/gtest.h>

#include <nlohmann/json.hpp>

#include "api/PostsController.hpp"
#include "test_helpers.hpp"

using json = nlohmann::json;
using namespace drogon;

namespace {

class PostsFlowTest : public TestHelpers::CoreBackedTest {
protected:
    Api::PostsController controller;
    std::string config_file_name() const override { return "post_flow_test_config.json"; }
    void config_overrides(json& cfg) override {
        cfg["database"]["migrations_enabled"] = true;
        cfg["database"]["migrations_dir"] = "migrations";
    }
};

TEST_F(PostsFlowTest, ListReturnsEnvelope) {
    HttpResponsePtr resp;
    controller.listPosts(TestHelpers::make_request(Get), [&](const HttpResponsePtr& r) { resp = r; });
    ASSERT_NE(resp, nullptr);
    // With AUTH_MODE=none the admin guard is a no-op, so this reaches the handler.
    EXPECT_EQ(resp->statusCode(), k200OK);
    auto body = json::parse(std::string(resp->body()));
    EXPECT_TRUE(body.contains("data"));
    EXPECT_TRUE(body.contains("total"));
}

}  // namespace
