/**
 * @file PostsController.hpp
 * @brief Post CRUD endpoints. Generated by scripts/new-resource.sh.
 *        Admin-gated; follows docs/CONVENTIONS.md.
 */

#pragma once

#include <drogon/HttpController.h>
#include <drogon/drogon.h>

#include <nlohmann/json.hpp>

#include "api/Guards.hpp"
#include "api/HandlerSupport.hpp"
#include "api/RequestUtils.hpp"
#include "api/Validation.hpp"
#include "domain/Post.hpp"
#include "repositories/PostRepository.hpp"
#include "security/Auth.hpp"
#include "security/Tokens.hpp"
#include "utils/ErrorResponse.hpp"
#include "utils/Time.hpp"

namespace Api {

using namespace drogon;
using json = nlohmann::json;

class PostsController : public HttpController<PostsController> {
public:
    METHOD_LIST_BEGIN
    // Admin CMS (ADMINISTER-gated): full CRUD over every post, drafts included.
    ADD_METHOD_TO(PostsController::listPosts, "/api/v1/posts", Get);
    ADD_METHOD_TO(PostsController::createPost, "/api/v1/posts", Post);
    ADD_METHOD_TO(PostsController::getPost, "/api/v1/posts/{1}", Get);
    ADD_METHOD_TO(PostsController::updatePost, "/api/v1/posts/{1}", Patch);
    ADD_METHOD_TO(PostsController::deletePost, "/api/v1/posts/{1}", Delete);
    ADD_METHOD_TO(PostsController::previewToken, "/api/v1/posts/{1}/preview-token", Post);
    // Public site (no auth): published posts only, addressed by slug.
    ADD_METHOD_TO(PostsController::publicListPosts, "/api/v1/public/posts", Get);
    ADD_METHOD_TO(PostsController::publicGetPost, "/api/v1/public/posts/{1}", Get);
    METHOD_LIST_END

    void listPosts(const HttpRequestPtr& req, std::function<void(const HttpResponsePtr&)>&& callback) {
        API_REQUIRE_ADMIN(req, callback);
        const auto page = parse_page_params(req, /*default_limit=*/50, /*max_limit=*/200);
        Repositories::AdminListFilter f;
        f.q = req->getParameter("q");
        f.status = req->getParameter("status");
        f.topic = req->getParameter("topic");
        f.tag = req->getParameter("tag");
        if (!f.status.empty() && f.status != "draft" && f.status != "published") {
            callback(ErrorResponse::bad_request("invalid_status", "status must be draft or published"));
            return;
        }
        Repositories::PostRepository repo;
        auto items = repo.list_admin(f, page.limit, page.offset);
        long total = repo.count_admin(f);
        json data = json::array();
        for (const auto& e : items)
            data.push_back(e);
        callback(Response::ok({{"data", data}, {"total", total}, {"limit", page.limit}, {"offset", page.offset}}));
    }

    void createPost(const HttpRequestPtr& req, std::function<void(const HttpResponsePtr&)>&& callback) {
        API_REQUIRE_ADMIN(req, callback);
        json body;
        if (!Validation::parse_body(req, body, callback))
            return;
        Repositories::PostInput in;
        if (!read_input(body, in, callback))
            return;
        with_repo_errors(callback, "createPost", [&] {
            Repositories::PostRepository repo;
            auto created = repo.create(in);
            auto resp = Response::ok({{"data", json(created)}});
            resp->setStatusCode(k201Created);
            callback(resp);
        });
    }

    void getPost(const HttpRequestPtr& req,
                 std::function<void(const HttpResponsePtr&)>&& callback,
                 const std::string& id) {
        API_REQUIRE_ADMIN(req, callback);
        if (!is_valid_uuid(id)) {
            callback(ErrorResponse::bad_request("invalid_uuid", "UUID format is invalid"));
            return;
        }
        Repositories::PostRepository repo;
        auto found = repo.find(id);
        if (!found) {
            callback(ErrorResponse::not_found("post"));
            return;
        }
        callback(Response::ok({{"data", json(*found)}}));
    }

    void updatePost(const HttpRequestPtr& req,
                    std::function<void(const HttpResponsePtr&)>&& callback,
                    const std::string& id) {
        API_REQUIRE_ADMIN(req, callback);
        if (!is_valid_uuid(id)) {
            callback(ErrorResponse::bad_request("invalid_uuid", "UUID format is invalid"));
            return;
        }
        json body;
        if (!Validation::parse_body(req, body, callback))
            return;
        Repositories::PostInput in;
        if (!read_input(body, in, callback))
            return;
        with_repo_errors(callback, "updatePost", [&] {
            Repositories::PostRepository repo;
            auto updated = repo.update(id, in);
            callback(Response::ok({{"data", json(updated)}}));
        });
    }

    void deletePost(const HttpRequestPtr& req,
                    std::function<void(const HttpResponsePtr&)>&& callback,
                    const std::string& id) {
        API_REQUIRE_ADMIN(req, callback);
        if (!is_valid_uuid(id)) {
            callback(ErrorResponse::bad_request("invalid_uuid", "UUID format is invalid"));
            return;
        }
        with_repo_errors(callback, "deletePost", [&] {
            Repositories::PostRepository repo;
            repo.remove(id);
            callback(Response::ok({{"message", "Post deleted"}}));
        });
    }

    // Draft preview: a stateless HMAC token (purpose=preview, sub=post id,
    // 1h TTL). Reusable within its TTL, nothing stored server-side; the link
    // works for anyone holding it — that's the point of "send to my phone".
    static constexpr std::chrono::seconds kPreviewTtl{3600};

    void previewToken(const HttpRequestPtr& req,
                      std::function<void(const HttpResponsePtr&)>&& callback,
                      const std::string& id) {
        API_REQUIRE_ADMIN(req, callback);
        if (!is_valid_uuid(id)) {
            callback(ErrorResponse::bad_request("invalid_uuid", "UUID format is invalid"));
            return;
        }
        Repositories::PostRepository repo;
        auto found = repo.find(id);
        if (!found) {
            callback(ErrorResponse::not_found("post"));
            return;
        }
        const auto token = Security::Tokens::issue(
            Security::Auth::get().config().jwt_secret, id, Security::Tokens::Purpose::Preview, kPreviewTtl);
        const auto exp = Utils::Time::epoch_to_iso8601(Utils::Time::now_epoch_seconds() + kPreviewTtl.count());
        callback(
            Response::ok({{"data", {{"url", "/blog/" + found->slug + "?preview=" + token}, {"expires_at", exp}}}}));
    }

    // Returns the post for slug honoring an optional ?preview= token:
    // published posts always; a draft only when the token verifies AND is
    // bound to this post. Shared with the SSR page controller.
    static std::optional<Domain::Post> resolve_post(const std::string& slug, const std::string& preview) {
        Repositories::PostRepository repo;
        if (preview.empty())
            return repo.find_published_by_slug(slug);
        auto any = repo.find_by_slug_any(slug);
        if (!any)
            return std::nullopt;
        if (any->status == "published")
            return any;
        auto vr = Security::Tokens::verify(
            Security::Auth::get().config().jwt_secret, preview, Security::Tokens::Purpose::Preview);
        if (vr.ok && vr.sub == any->id)
            return any;
        return std::nullopt;  // invalid/expired/foreign token behaves like 404
    }

    // ── Public site (unauthenticated) ─────────────────────────────────────
    void publicListPosts(const HttpRequestPtr& req, std::function<void(const HttpResponsePtr&)>&& callback) {
        // Hybrid contract (spec 2026-07-25): server-side filters + 1-based
        // paging; facets embedded on demand so the index needs exactly one
        // request per interaction. limit is hard-clamped to 50 — the old
        // fetch-the-whole-feed ?limit=1000 pattern is gone.
        const int limit = clamp_int(req->getParameter("limit"), 10, 1, 50);
        const int page = clamp_int(req->getParameter("page"), 1, 1, 1000000);
        Repositories::PublicListFilter f;
        f.topic = req->getParameter("topic");
        f.tag = req->getParameter("tag");
        f.q = req->getParameter("q");

        Repositories::PostRepository repo;
        auto items = repo.list_published_cards(f, limit, (page - 1) * limit);
        long total = repo.count_published(f);
        json out = {{"items", json::array()}, {"page", page}, {"limit", limit}, {"total", total}};
        for (const auto& e : items)
            out["items"].push_back(e);

        if (req->getParameter("include").find("facets") != std::string::npos) {
            auto [topics, tags] = repo.facets(f);
            json jt = json::array(), jg = json::array();
            for (const auto& t : topics)
                jt.push_back({{"name", t.name}, {"count", t.count}});
            for (const auto& t : tags)
                jg.push_back({{"name", t.name}, {"count", t.count}});
            out["facets"] = {{"topics", jt}, {"tags", jg}};
        }
        callback(Response::ok(out));
    }

    void publicGetPost(const HttpRequestPtr& req,
                       std::function<void(const HttpResponsePtr&)>&& callback,
                       const std::string& slug) {
        Repositories::PostRepository repo;
        auto found = resolve_post(slug, req->getParameter("preview"));
        if (!found) {
            callback(ErrorResponse::not_found("post"));
            return;
        }
        json data = json(*found);
        if (req->getParameter("include").find("adjacent") != std::string::npos) {
            auto [prev, next] = repo.find_adjacent(found->id);
            data["adjacent"] = {{"prev", prev ? json{{"slug", prev->slug}, {"title", prev->title}} : json(nullptr)},
                                {"next", next ? json{{"slug", next->slug}, {"title", next->title}} : json(nullptr)}};
        }
        callback(Response::ok({{"data", data}}));
    }

private:
    // Parse + validate a create/update body into PostInput. On failure it
    // sends a 400 via @p callback and returns false (caller must stop).
    static bool read_input(const json& body,
                           Repositories::PostInput& in,
                           const std::function<void(const HttpResponsePtr&)>& callback) {
        Validation::Errors errs;
        Validation::require(errs, body, "slug");
        Validation::require(errs, body, "title");
        Validation::string_length(errs, body, "slug", 1, 160);
        Validation::string_length(errs, body, "title", 1, 255);
        Validation::string_length(errs, body, "topic", 0, 80);
        Validation::one_of(errs, body, "status", {"draft", "published"});
        // tags: optional array of non-empty keyword strings. Stored comma-joined,
        // so a comma inside a tag would corrupt the round-trip — reject it.
        std::vector<std::string> tags;
        if (body.contains("tags") && !body["tags"].is_null()) {
            if (!body["tags"].is_array()) {
                errs.add("tags", "not_array", "must be an array of strings");
            } else {
                for (const auto& t : body["tags"]) {
                    if (!t.is_string()) {
                        errs.add("tags", "not_string", "each tag must be a string");
                        break;
                    }
                    std::string s = t.get<std::string>();
                    std::size_t b = s.find_first_not_of(" \t");
                    std::size_t e = s.find_last_not_of(" \t");
                    if (b == std::string::npos)
                        continue;  // blank tag → skip silently
                    s = s.substr(b, e - b + 1);
                    if (s.size() > 40) {
                        errs.add("tags", "too_long", "each tag max length 40");
                        break;
                    }
                    if (s.find(',') != std::string::npos || s.find('\n') != std::string::npos ||
                        s.find('\r') != std::string::npos) {
                        errs.add("tags", "invalid", "a tag must not contain commas or line breaks");
                        break;
                    }
                    tags.push_back(std::move(s));
                }
            }
        }
        // Optional fields must be strings when present — `body.value(k, "")`
        // throws type_error.306 on a non-string (number/bool), which would
        // otherwise escape the handler as a bare 500 instead of a 400.
        for (const char* k : {"summary", "body", "status", "topic"})
            if (body.contains(k) && !body[k].is_null() && !body[k].is_string())
                errs.add(k, "not_string", std::string(k) + " must be a string");
        // Slug is the public URL key: constrain it to a clean path segment so a
        // slug with '/', spaces, '#', '?' can't create an unreachable post.
        if (body.contains("slug") && body["slug"].is_string()) {
            const std::string s = body["slug"].get<std::string>();
            bool ok = !s.empty();
            for (char c : s)
                if (!((c >= 'a' && c <= 'z') || (c >= '0' && c <= '9') || c == '-'))
                    ok = false;
            if (!ok || s.front() == '-' || s.back() == '-')
                errs.add("slug",
                         "invalid",
                         "slug must be lowercase letters, digits and hyphens (no leading/trailing hyphen)");
        }
        if (errs.any()) {
            callback(Validation::response_400(errs));
            return false;
        }
        in.slug = body["slug"].get<std::string>();
        in.title = body["title"].get<std::string>();
        in.summary = body.value("summary", std::string{});
        in.body = body.value("body", std::string{});
        in.status = body.value("status", std::string{"draft"});
        in.topic = body.value("topic", std::string{});
        in.tags = std::move(tags);
        return true;
    }
};

}  // namespace Api
