/**
 * @file PostsController.hpp
 * @brief Post CRUD endpoints. Generated by scripts/new-resource.sh.
 *        Admin-gated; follows docs/CONVENTIONS.md.
 */

#pragma once

#include <drogon/HttpController.h>
#include <drogon/drogon.h>

#include <nlohmann/json.hpp>

#include "api/Guards.hpp"
#include "api/HandlerSupport.hpp"
#include "api/RequestUtils.hpp"
#include "api/Validation.hpp"
#include "domain/Post.hpp"
#include "repositories/PostRepository.hpp"
#include "utils/ErrorResponse.hpp"

namespace Api {

using namespace drogon;
using json = nlohmann::json;

class PostsController : public HttpController<PostsController> {
public:
    METHOD_LIST_BEGIN
    // Admin CMS (ADMINISTER-gated): full CRUD over every post, drafts included.
    ADD_METHOD_TO(PostsController::listPosts, "/api/v1/posts", Get);
    ADD_METHOD_TO(PostsController::createPost, "/api/v1/posts", Post);
    ADD_METHOD_TO(PostsController::getPost, "/api/v1/posts/{1}", Get);
    ADD_METHOD_TO(PostsController::updatePost, "/api/v1/posts/{1}", Put);
    ADD_METHOD_TO(PostsController::deletePost, "/api/v1/posts/{1}", Delete);
    // Public site (no auth): published posts only, addressed by slug.
    ADD_METHOD_TO(PostsController::publicListPosts, "/api/v1/public/posts", Get);
    ADD_METHOD_TO(PostsController::publicGetPost, "/api/v1/public/posts/{1}", Get);
    METHOD_LIST_END

    void listPosts(const HttpRequestPtr& req, std::function<void(const HttpResponsePtr&)>&& callback) {
        API_REQUIRE_ADMIN(req, callback);
        const auto page = parse_page_params(req, /*default_limit=*/50, /*max_limit=*/200);
        Repositories::PostRepository repo;
        auto items = repo.list(page.limit, page.offset);
        long total = repo.count();
        json data = json::array();
        for (const auto& e : items)
            data.push_back(e);
        callback(Response::ok({{"data", data}, {"total", total}, {"limit", page.limit}, {"offset", page.offset}}));
    }

    void createPost(const HttpRequestPtr& req, std::function<void(const HttpResponsePtr&)>&& callback) {
        API_REQUIRE_ADMIN(req, callback);
        json body;
        if (!Validation::parse_body(req, body, callback))
            return;
        Repositories::PostInput in;
        if (!read_input(body, in, callback))
            return;
        with_repo_errors(callback, "createPost", [&] {
            Repositories::PostRepository repo;
            auto created = repo.create(in);
            auto resp = Response::ok({{"data", json(created)}});
            resp->setStatusCode(k201Created);
            callback(resp);
        });
    }

    void getPost(const HttpRequestPtr& req,
                 std::function<void(const HttpResponsePtr&)>&& callback,
                 const std::string& id) {
        API_REQUIRE_ADMIN(req, callback);
        if (!is_valid_uuid(id)) {
            callback(ErrorResponse::bad_request("invalid_uuid", "UUID format is invalid"));
            return;
        }
        Repositories::PostRepository repo;
        auto found = repo.find(id);
        if (!found) {
            callback(ErrorResponse::not_found("post"));
            return;
        }
        callback(Response::ok({{"data", json(*found)}}));
    }

    void updatePost(const HttpRequestPtr& req,
                    std::function<void(const HttpResponsePtr&)>&& callback,
                    const std::string& id) {
        API_REQUIRE_ADMIN(req, callback);
        if (!is_valid_uuid(id)) {
            callback(ErrorResponse::bad_request("invalid_uuid", "UUID format is invalid"));
            return;
        }
        json body;
        if (!Validation::parse_body(req, body, callback))
            return;
        Repositories::PostInput in;
        if (!read_input(body, in, callback))
            return;
        with_repo_errors(callback, "updatePost", [&] {
            Repositories::PostRepository repo;
            auto updated = repo.update(id, in);
            callback(Response::ok({{"data", json(updated)}}));
        });
    }

    void deletePost(const HttpRequestPtr& req,
                    std::function<void(const HttpResponsePtr&)>&& callback,
                    const std::string& id) {
        API_REQUIRE_ADMIN(req, callback);
        if (!is_valid_uuid(id)) {
            callback(ErrorResponse::bad_request("invalid_uuid", "UUID format is invalid"));
            return;
        }
        with_repo_errors(callback, "deletePost", [&] {
            Repositories::PostRepository repo;
            repo.remove(id);
            callback(Response::ok({{"message", "Post deleted"}}));
        });
    }

    // ── Public site (unauthenticated) ─────────────────────────────────────
    void publicListPosts(const HttpRequestPtr& req, std::function<void(const HttpResponsePtr&)>&& callback) {
        const auto page = parse_page_params(req, /*default_limit=*/20, /*max_limit=*/100);
        Repositories::PostRepository repo;
        auto items = repo.list_published(page.limit, page.offset);
        json data = json::array();
        for (const auto& e : items)
            data.push_back(e);
        callback(Response::ok({{"data", data}, {"limit", page.limit}, {"offset", page.offset}}));
    }

    void publicGetPost(const HttpRequestPtr& req,
                       std::function<void(const HttpResponsePtr&)>&& callback,
                       const std::string& slug) {
        Repositories::PostRepository repo;
        auto found = repo.find_published_by_slug(slug);
        if (!found) {
            callback(ErrorResponse::not_found("post"));
            return;
        }
        callback(Response::ok({{"data", json(*found)}}));
    }

private:
    // Parse + validate a create/update body into PostInput. On failure it
    // sends a 400 via @p callback and returns false (caller must stop).
    static bool read_input(const json& body,
                           Repositories::PostInput& in,
                           const std::function<void(const HttpResponsePtr&)>& callback) {
        Validation::Errors errs;
        Validation::require(errs, body, "slug");
        Validation::require(errs, body, "title");
        Validation::string_length(errs, body, "slug", 1, 160);
        Validation::string_length(errs, body, "title", 1, 255);
        Validation::one_of(errs, body, "status", {"draft", "published"});
        if (errs.any()) {
            callback(Validation::response_400(errs));
            return false;
        }
        in.slug = body["slug"].get<std::string>();
        in.title = body["title"].get<std::string>();
        in.summary = body.value("summary", std::string{});
        in.body = body.value("body", std::string{});
        in.status = body.value("status", std::string{"draft"});
        return true;
    }
};

}  // namespace Api
