/**
 * @file PostRepository.hpp
 * @brief All SQL touching `posts` lives here. Generated by
 *        scripts/new-resource.sh. Controllers never touch pqxx directly.
 */

#pragma once

#include <optional>
#include <pqxx/pqxx>
#include <stdexcept>
#include <string>
#include <vector>

#include "database/Database.hpp"
#include "domain/Post.hpp"
#include "repositories/CrudBase.hpp"
#include "repositories/SqlErrors.hpp"

namespace Repositories {

struct DuplicatePost : std::runtime_error {
    DuplicatePost() : std::runtime_error("post already exists") {}
};

struct PostNotFound : std::runtime_error {
    PostNotFound() : std::runtime_error("post not found") {}
};

// Writable fields parsed from a request body (id/timestamps are server-owned;
// published_at is derived from status transitions, not set directly).
struct PostInput {
    std::string slug;
    std::string title;
    std::string summary;
    std::string body;
    std::string status;             // draft | published
    std::string topic;              // section label
    std::vector<std::string> tags;  // keyword tags (stored comma-joined)
};

class PostRepository : public CrudBase<PostRepository, Domain::Post, std::string> {
public:
    // CrudBase supplies find(id) / list(limit, offset) / count() from these
    // four constants — only the bespoke writes/reads below are hand-written.
    static constexpr const char* kTable = "posts";
    static constexpr const char* kColumns =
        "id, slug, title, summary, body, status, topic, tags, published_at, created_at, updated_at";
    static constexpr const char* kIdColumn = "id";
    static constexpr const char* kOrderBy = "created_at DESC";

    Domain::Post create(const PostInput& in) {
        // published_at is server-chosen (not user input), so pick the literal in
        // C++ rather than reuse the status parameter in a CASE — Postgres rejects
        // a parameter inferred as two types (varchar column + text comparison).
        const char* published_expr = in.status == "published" ? "now()" : "NULL";
        return detail::translate_sql(
            [&] {
                return Database::get().execute_write([&](auto& txn) {
                    auto r = txn.exec_params(
                        std::string("INSERT INTO posts (slug, title, summary, body, status, topic, tags, published_at) "
                                    "VALUES ($1, $2, $3, $4, $5, $6, $7, ") +
                            published_expr + ") RETURNING " + kColumns,
                        in.slug,
                        in.title,
                        in.summary,
                        in.body,
                        in.status,
                        in.topic,
                        Domain::join_tags(in.tags));
                    return Domain::Post::from_row(r[0]);
                });
            },
            [](std::string_view ss) {
                if (ss == "23505")
                    throw DuplicatePost{};
            });
    }

    Domain::Post update(const std::string& id, const PostInput& in) {
        // First publish stamps published_at; an already-published edit keeps it
        // (COALESCE); back to draft clears it. Chosen in C++ so the status param
        // isn't reused in a CASE (Postgres rejects a two-typed parameter).
        const char* published_expr = in.status == "published" ? "COALESCE(published_at, now())" : "NULL";
        return detail::translate_sql(
            [&] {
                return Database::get().execute_write([&](auto& txn) {
                    auto r = txn.exec_params(
                        std::string("UPDATE posts SET slug = $2, title = $3, summary = $4, body = $5, status = $6, "
                                    "topic = $7, tags = $8, published_at = ") +
                            published_expr + " WHERE id = $1 RETURNING " + kColumns,
                        id,
                        in.slug,
                        in.title,
                        in.summary,
                        in.body,
                        in.status,
                        in.topic,
                        Domain::join_tags(in.tags));
                    if (r.empty())
                        throw PostNotFound{};
                    return Domain::Post::from_row(r[0]);
                });
            },
            [](std::string_view ss) {
                if (ss == "23505")
                    throw DuplicatePost{};
            });
    }

    void remove(const std::string& id) {
        Database::get().execute_write([&](auto& txn) {
            auto r = txn.exec_params("DELETE FROM posts WHERE id = $1 RETURNING id", id);
            if (r.empty())
                throw PostNotFound{};
            return 0;
        });
    }

    // ── Public reads (published only) ─────────────────────────────────────
    // Used by the unauthenticated public site. Drafts are never exposed here.
    std::vector<Domain::Post> list_published(int limit = 50, int offset = 0) {
        return Database::get().execute_read([&](auto& txn) {
            auto r = txn.exec_params(
                std::string("SELECT ") + kColumns +
                    " FROM posts WHERE status = 'published' ORDER BY published_at DESC LIMIT $1 OFFSET $2",
                limit,
                offset);
            std::vector<Domain::Post> out;
            out.reserve(r.size());
            for (const auto& row : r)
                out.push_back(Domain::Post::from_row(row));
            return out;
        });
    }

    std::optional<Domain::Post> find_published_by_slug(const std::string& slug) {
        return Database::get().execute_read([&](auto& txn) -> std::optional<Domain::Post> {
            auto r = txn.exec_params(
                std::string("SELECT ") + kColumns + " FROM posts WHERE slug = $1 AND status = 'published'", slug);
            if (r.empty())
                return std::nullopt;
            return Domain::Post::from_row(r[0]);
        });
    }
};

}  // namespace Repositories
