/**
 * @file PostRepository.hpp
 * @brief All SQL touching `posts` lives here. Generated by
 *        scripts/new-resource.sh. Controllers never touch pqxx directly.
 */

#pragma once

#include <optional>
#include <stdexcept>
#include <string>
#include <vector>

#include <pqxx/pqxx>

#include "database/Database.hpp"
#include "domain/Post.hpp"
#include "repositories/CrudBase.hpp"
#include "repositories/SqlErrors.hpp"

namespace Repositories {

struct DuplicatePost : std::runtime_error {
    DuplicatePost() : std::runtime_error("post already exists") {}
};

struct PostNotFound : std::runtime_error {
    PostNotFound() : std::runtime_error("post not found") {}
};

// Writable fields parsed from a request body (id/timestamps are server-owned;
// published_at is derived from status transitions, not set directly).
struct PostInput {
    std::string slug;
    std::string title;
    std::string summary;
    std::string body;
    std::string status;  // draft | published
};

class PostRepository : public CrudBase<PostRepository, Domain::Post, std::string> {
public:
    // CrudBase supplies find(id) / list(limit, offset) / count() from these
    // four constants — only the bespoke writes/reads below are hand-written.
    static constexpr const char* kTable = "posts";
    static constexpr const char* kColumns =
        "id, slug, title, summary, body, status, published_at, created_at, updated_at";
    static constexpr const char* kIdColumn = "id";
    static constexpr const char* kOrderBy = "created_at DESC";

    Domain::Post create(const PostInput& in) {
        return detail::translate_sql(
            [&] {
                return Database::get().execute_write([&](auto& txn) {
                    // published_at is stamped now() the moment a row is created
                    // already published; drafts keep it NULL until they go live.
                    auto r = txn.exec_params(
                        std::string("INSERT INTO posts (slug, title, summary, body, status, published_at) "
                                    "VALUES ($1, $2, $3, $4, $5, "
                                    "CASE WHEN $5 = 'published' THEN now() ELSE NULL END) RETURNING ") +
                            kColumns,
                        in.slug,
                        in.title,
                        in.summary,
                        in.body,
                        in.status);
                    return Domain::Post::from_row(r[0]);
                });
            },
            [](std::string_view ss) {
                if (ss == "23505")
                    throw DuplicatePost{};
            });
    }

    Domain::Post update(const std::string& id, const PostInput& in) {
        return detail::translate_sql(
            [&] {
                return Database::get().execute_write([&](auto& txn) {
                    // First publish stamps published_at; back to draft clears it;
                    // edits to an already-published post leave it untouched.
                    auto r = txn.exec_params(
                        std::string("UPDATE posts SET slug = $2, title = $3, summary = $4, body = $5, status = $6, "
                                    "published_at = CASE "
                                    "WHEN $6 = 'published' AND published_at IS NULL THEN now() "
                                    "WHEN $6 = 'draft' THEN NULL "
                                    "ELSE published_at END "
                                    "WHERE id = $1 RETURNING ") +
                            kColumns,
                        id,
                        in.slug,
                        in.title,
                        in.summary,
                        in.body,
                        in.status);
                    if (r.empty())
                        throw PostNotFound{};
                    return Domain::Post::from_row(r[0]);
                });
            },
            [](std::string_view ss) {
                if (ss == "23505")
                    throw DuplicatePost{};
            });
    }

    void remove(const std::string& id) {
        Database::get().execute_write([&](auto& txn) {
            auto r = txn.exec_params("DELETE FROM posts WHERE id = $1 RETURNING id", id);
            if (r.empty())
                throw PostNotFound{};
            return 0;
        });
    }

    // ── Public reads (published only) ─────────────────────────────────────
    // Used by the unauthenticated public site. Drafts are never exposed here.
    std::vector<Domain::Post> list_published(int limit = 50, int offset = 0) {
        return Database::get().execute_read([&](auto& txn) {
            auto r = txn.exec_params(
                std::string("SELECT ") + kColumns +
                    " FROM posts WHERE status = 'published' ORDER BY published_at DESC LIMIT $1 OFFSET $2",
                limit,
                offset);
            std::vector<Domain::Post> out;
            out.reserve(r.size());
            for (const auto& row : r)
                out.push_back(Domain::Post::from_row(row));
            return out;
        });
    }

    std::optional<Domain::Post> find_published_by_slug(const std::string& slug) {
        return Database::get().execute_read([&](auto& txn) -> std::optional<Domain::Post> {
            auto r = txn.exec_params(
                std::string("SELECT ") + kColumns + " FROM posts WHERE slug = $1 AND status = 'published'", slug);
            if (r.empty())
                return std::nullopt;
            return Domain::Post::from_row(r[0]);
        });
    }
};

}  // namespace Repositories
