/**
 * @file PostRepository.hpp
 * @brief All SQL touching `posts` lives here. Generated by
 *        scripts/new-resource.sh. Controllers never touch pqxx directly.
 */

#pragma once

#include <optional>
#include <pqxx/pqxx>
#include <stdexcept>
#include <string>
#include <utility>
#include <vector>

#include "database/Database.hpp"
#include "domain/Post.hpp"
#include "repositories/CrudBase.hpp"
#include "repositories/RepoErrors.hpp"
#include "repositories/SqlErrors.hpp"

namespace Repositories {

// Derive from the generic repo bases so Api::with_repo_errors maps them to
// 409 / 404 instead of a bare 500 (see RepoErrors.hpp / HandlerSupport.hpp).
struct DuplicatePost : ConflictError {
    DuplicatePost() : ConflictError("slug_taken", "a post with that slug already exists") {}
};

struct PostNotFound : NotFoundError {
    PostNotFound() : NotFoundError("post") {}
};

// Public list filter (hybrid contract, spec 2026-07-25): every field optional.
struct PublicListFilter {
    std::string topic;  // exact; "Other" also matches blank topics
    std::string tag;    // exact tag membership (comma-joined storage)
    std::string q;      // ILIKE over title+summary
};

// Admin list filter: like the public one but sees drafts, filters by status,
// and q additionally covers the slug (admins look posts up by slug).
struct AdminListFilter {
    std::string q;
    std::string status;  // "" | draft | published
    std::string topic;
    std::string tag;
};

// Writable fields parsed from a request body (id/timestamps are server-owned;
// published_at is derived from status transitions, not set directly).
struct PostInput {
    std::string slug;
    std::string title;
    std::string summary;
    std::string body;
    std::string status;             // draft | published
    std::string topic;              // section label
    std::vector<std::string> tags;  // keyword tags (stored comma-joined)
};

class PostRepository : public CrudBase<PostRepository, Domain::Post, std::string> {
public:
    // CrudBase supplies find(id) / list(limit, offset) / count() from these
    // four constants — only the bespoke writes/reads below are hand-written.
    static constexpr const char* kTable = "posts";
    static constexpr const char* kColumns =
        "id, slug, title, summary, body, status, topic, tags, published_at, created_at, updated_at";
    static constexpr const char* kIdColumn = "id";
    static constexpr const char* kOrderBy = "created_at DESC";

    Domain::Post create(const PostInput& in) {
        // published_at is server-chosen (not user input), so pick the literal in
        // C++ rather than reuse the status parameter in a CASE — Postgres rejects
        // a parameter inferred as two types (varchar column + text comparison).
        const char* published_expr = in.status == "published" ? "now()" : "NULL";
        return detail::translate_sql(
            [&] {
                return Database::get().execute_write([&](auto& txn) {
                    auto r = txn.exec_params(
                        std::string("INSERT INTO posts (slug, title, summary, body, status, topic, tags, published_at) "
                                    "VALUES ($1, $2, $3, $4, $5, $6, $7, ") +
                            published_expr + ") RETURNING " + kColumns,
                        in.slug,
                        in.title,
                        in.summary,
                        in.body,
                        in.status,
                        in.topic,
                        Domain::join_tags(in.tags));
                    return Domain::Post::from_row(r[0]);
                });
            },
            [](std::string_view ss) {
                if (ss == "23505")
                    throw DuplicatePost{};
            });
    }

    Domain::Post update(const std::string& id, const PostInput& in) {
        // First publish stamps published_at; an already-published edit keeps it
        // (COALESCE); back to draft clears it. Chosen in C++ so the status param
        // isn't reused in a CASE (Postgres rejects a two-typed parameter).
        const char* published_expr = in.status == "published" ? "COALESCE(published_at, now())" : "NULL";
        return detail::translate_sql(
            [&] {
                return Database::get().execute_write([&](auto& txn) {
                    auto r = txn.exec_params(
                        std::string("UPDATE posts SET slug = $2, title = $3, summary = $4, body = $5, status = $6, "
                                    "topic = $7, tags = $8, published_at = ") +
                            published_expr + " WHERE id = $1 RETURNING " + kColumns,
                        id,
                        in.slug,
                        in.title,
                        in.summary,
                        in.body,
                        in.status,
                        in.topic,
                        Domain::join_tags(in.tags));
                    if (r.empty())
                        throw PostNotFound{};
                    return Domain::Post::from_row(r[0]);
                });
            },
            [](std::string_view ss) {
                if (ss == "23505")
                    throw DuplicatePost{};
            });
    }

    void remove(const std::string& id) {
        Database::get().execute_write([&](auto& txn) {
            auto r = txn.exec_params("DELETE FROM posts WHERE id = $1 RETURNING id", id);
            if (r.empty())
                throw PostNotFound{};
            return 0;
        });
    }

    // ── Public reads (published only) ─────────────────────────────────────
    // Used by the unauthenticated public site. Drafts are never exposed here.

private:
    // Escape LIKE metacharacters so a literal '%' in q can't scan everything.
    static std::string escape_like(const std::string& s) {
        std::string out;
        out.reserve(s.size() + 4);
        for (char c : s) {
            if (c == '%' || c == '_' || c == '\\')
                out += '\\';
            out += c;
        }
        return out;
    }

    // WHERE clause for public reads. Values are inlined via the underlying
    // pqxx transaction's esc() (TracingTxn::raw()) — pqxx has no named params
    // and the clause shape varies per filter.
    template <typename Txn>
    static std::string public_where(Txn& txn, const PublicListFilter& f) {
        std::string w = "status = 'published'";
        if (!f.topic.empty()) {
            if (f.topic == "Other")
                w += " AND (btrim(topic) = '' OR topic = 'Other')";
            else
                w += " AND topic = '" + txn.raw().esc(f.topic) + "'";
        }
        if (!f.tag.empty())
            w += " AND (',' || tags || ',') LIKE ('%,' || '" + txn.raw().esc(escape_like(f.tag)) + "' || ',%')";
        if (!f.q.empty()) {
            const std::string qq = txn.raw().esc(escape_like(f.q));
            w += " AND (title ILIKE '%" + qq + "%' OR summary ILIKE '%" + qq + "%')";
        }
        return w;
    }

private:
    template <typename Txn>
    static std::string admin_where(Txn& txn, const AdminListFilter& f) {
        std::string w = "TRUE";
        if (!f.status.empty())
            w += " AND status = '" + txn.raw().esc(f.status) + "'";
        if (!f.topic.empty())
            w += " AND topic = '" + txn.raw().esc(f.topic) + "'";
        if (!f.tag.empty())
            w += " AND (',' || tags || ',') LIKE ('%,' || '" + txn.raw().esc(escape_like(f.tag)) + "' || ',%')";
        if (!f.q.empty()) {
            const std::string qq = txn.raw().esc(escape_like(f.q));
            w += " AND (title ILIKE '%" + qq + "%' OR slug ILIKE '%" + qq + "%' OR summary ILIKE '%" + qq + "%')";
        }
        return w;
    }

public:
    std::vector<Domain::Post> list_admin(const AdminListFilter& f, int limit, int offset) {
        return Database::get().execute_read([&](auto& txn) {
            auto r = txn.exec(std::string("SELECT ") + kColumns + " FROM posts WHERE " + admin_where(txn, f) +
                              " ORDER BY created_at DESC LIMIT " + std::to_string(limit) + " OFFSET " +
                              std::to_string(offset));
            std::vector<Domain::Post> out;
            out.reserve(r.size());
            for (const auto& row : r)
                out.push_back(Domain::Post::from_row(row));
            return out;
        });
    }

    long count_admin(const AdminListFilter& f) {
        return Database::get().execute_read([&](auto& txn) {
            auto r = txn.exec("SELECT count(*) FROM posts WHERE " + admin_where(txn, f));
            return r[0][0].template as<long>();
        });
    }

    // Lightweight list projection: no body column, and read_mins computed in
    // SQL (ceil(words / 200), floor 1) so the public index ships without any
    // Markdown bodies. Word count = whitespace-split token count of the trimmed
    // body, matching the frontend's old readMins() formula.
    std::vector<Domain::PostCard> list_published_cards(const PublicListFilter& f, int limit, int offset) {
        return Database::get().execute_read([&](auto& txn) {
            auto r = txn.exec(
                "SELECT slug, title, summary, topic, tags, published_at, "
                "GREATEST(1, CEIL(array_length(regexp_split_to_array(trim(body), '\\s+'), 1)::numeric / 200))::int "
                "AS read_mins FROM posts WHERE " +
                public_where(txn, f) + " ORDER BY published_at DESC, id DESC LIMIT " + std::to_string(limit) +
                " OFFSET " + std::to_string(offset));
            std::vector<Domain::PostCard> out;
            out.reserve(r.size());
            for (const auto& row : r)
                out.push_back(Domain::PostCard::from_row(row));
            return out;
        });
    }

    long count_published(const PublicListFilter& f = {}) {
        return Database::get().execute_read([&](auto& txn) {
            auto r = txn.exec("SELECT count(*) FROM posts WHERE " + public_where(txn, f));
            return r[0][0].template as<long>();
        });
    }

    // Facets over the CURRENT filter (the index chips reflect the result set):
    // topics with counts (blank topic groups as "Other"), and the top tags.
    struct FacetRow {
        std::string name;
        long count = 0;
    };
    std::pair<std::vector<FacetRow>, std::vector<FacetRow>> facets(const PublicListFilter& f) {
        return Database::get().execute_read([&](auto& txn) {
            std::pair<std::vector<FacetRow>, std::vector<FacetRow>> out;
            auto topics = txn.exec(
                "SELECT COALESCE(NULLIF(btrim(topic), ''), 'Other') AS name, count(*)::bigint AS c "
                "FROM posts WHERE " +
                public_where(txn, f) + " GROUP BY 1 ORDER BY c DESC, name ASC");
            for (const auto& row : topics)
                out.first.push_back({row["name"].template as<std::string>(), row["c"].template as<long>()});
            auto tags = txn.exec(
                "SELECT btrim(t) AS name, count(*)::bigint AS c FROM posts, "
                "LATERAL unnest(string_to_array(tags, ',')) AS t "
                "WHERE " +
                public_where(txn, f) +
                " AND btrim(t) <> '' "
                "GROUP BY 1 ORDER BY c DESC, name ASC LIMIT 30");
            for (const auto& row : tags)
                out.second.push_back({row["name"].template as<std::string>(), row["c"].template as<long>()});
            return out;
        });
    }

    // Slug + last-modified date for every published post, newest first — feeds
    // the dynamic /sitemap.xml. lastmod prefers updated_at, falling back to
    // published_at, truncated to a date (W3C sitemap date form).
    struct SitemapEntry {
        std::string slug;
        std::string lastmod;  // YYYY-MM-DD
    };
    std::vector<SitemapEntry> list_published_for_sitemap() {
        return Database::get().execute_read([&](auto& txn) {
            auto r = txn.exec_params(
                "SELECT slug, to_char(COALESCE(updated_at, published_at), 'YYYY-MM-DD') AS lastmod "
                "FROM posts WHERE status = 'published' ORDER BY published_at DESC");
            std::vector<SitemapEntry> out;
            out.reserve(r.size());
            for (const auto& row : r)
                out.push_back({row["slug"].template as<std::string>(),
                               row["lastmod"].is_null() ? std::string{} : row["lastmod"].template as<std::string>()});
            return out;
        });
    }

    // Prev (older) / next (newer) published neighbours in the public feed
    // order (published_at DESC). (published_at, id) row comparison breaks
    // equal-timestamp ties deterministically.
    struct AdjacentRef {
        std::string slug;
        std::string title;
    };
    std::pair<std::optional<AdjacentRef>, std::optional<AdjacentRef>> find_adjacent(const std::string& id) {
        return Database::get().execute_read([&](auto& txn) {
            std::pair<std::optional<AdjacentRef>, std::optional<AdjacentRef>> out;
            auto prev = txn.exec_params(  // older
                "SELECT slug, title FROM posts WHERE status='published' AND "
                "(published_at, id) < (SELECT published_at, id FROM posts WHERE id=$1) "
                "ORDER BY published_at DESC, id DESC LIMIT 1",
                id);
            if (!prev.empty())
                out.first = AdjacentRef{prev[0]["slug"].template as<std::string>(),
                                        prev[0]["title"].template as<std::string>()};
            auto next = txn.exec_params(  // newer
                "SELECT slug, title FROM posts WHERE status='published' AND "
                "(published_at, id) > (SELECT published_at, id FROM posts WHERE id=$1) "
                "ORDER BY published_at ASC, id ASC LIMIT 1",
                id);
            if (!next.empty())
                out.second = AdjacentRef{next[0]["slug"].template as<std::string>(),
                                         next[0]["title"].template as<std::string>()};
            return out;
        });
    }

    std::optional<Domain::Post> find_published_by_slug(const std::string& slug) {
        return Database::get().execute_read([&](auto& txn) -> std::optional<Domain::Post> {
            auto r = txn.exec_params(
                std::string("SELECT ") + kColumns + " FROM posts WHERE slug = $1 AND status = 'published'", slug);
            if (r.empty())
                return std::nullopt;
            return Domain::Post::from_row(r[0]);
        });
    }

    // Any status — used only by the draft-preview path, which gates access on
    // a signed token bound to the post id. Never expose without that check.
    std::optional<Domain::Post> find_by_slug_any(const std::string& slug) {
        return Database::get().execute_read([&](auto& txn) -> std::optional<Domain::Post> {
            auto r = txn.exec_params(std::string("SELECT ") + kColumns + " FROM posts WHERE slug = $1", slug);
            if (r.empty())
                return std::nullopt;
            return Domain::Post::from_row(r[0]);
        });
    }
};

}  // namespace Repositories
