#!/usr/bin/env bash
#
# Create the next NNN_<slug>.sql migration file in migrations/.
#
# Usage:
#   ./scripts/new-migration.sh <description> [--table <table>]
#
# Example:
#   ./scripts/new-migration.sh add_users_table
#   ./scripts/new-migration.sh "add posts published_at"
#   ./scripts/new-migration.sh add_products_table --table products
#
# Picks the next zero-padded version number (NNN, 3 digits) by scanning
# existing files in migrations/. Slugifies the description (lowercase,
# spaces/underscores → "_", non-[a-z0-9_] dropped). Refuses to overwrite
# an existing file.
#
# With --table <table>, emits a ready-to-run CREATE TABLE skeleton for the
# stub shape generated by scripts/new-resource.sh (id UUID / name / created_at /
# updated_at) plus an updated_at trigger wired to the shared touch_updated_at()
# function from migrations/000_updated_at_trigger.sql. Without it, the body is a
# commented skeleton you fill in by hand.
set -euo pipefail

TABLE=""
ARGS=()
while [[ $# -gt 0 ]]; do
    case "$1" in
    --table)
        if [[ $# -lt 2 ]]; then
            echo "ERROR: --table requires a value" >&2
            exit 2
        fi
        TABLE="$2"
        shift 2
        ;;
    --table=*)
        TABLE="${1#--table=}"
        shift
        ;;
    *)
        ARGS+=("$1")
        shift
        ;;
    esac
done
set -- "${ARGS[@]+"${ARGS[@]}"}"

if [[ $# -lt 1 ]]; then
    echo "Usage: $0 <description> [--table <table>]" >&2
    echo "Example: $0 add_users_table" >&2
    exit 1
fi

if [[ -n "$TABLE" && ! "$TABLE" =~ ^[a-z_][a-z0-9_]*$ ]]; then
    echo "ERROR: --table must be a valid SQL identifier (lower snake_case), got '$TABLE'" >&2
    exit 2
fi

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
DIR="$ROOT/migrations"
mkdir -p "$DIR"

# Find next version: max existing NNN + 1, default 001.
LAST=$(find "$DIR" -maxdepth 1 -type f -name '[0-9][0-9][0-9]_*.sql' |
    sed -E 's|.*/([0-9]{3})_.*|\1|' |
    sort -n |
    tail -1 || true)
if [[ -z "$LAST" ]]; then
    NEXT="001"
else
    NEXT=$(printf '%03d' $((10#$LAST + 1)))
fi

# Slugify description.
DESC_RAW="$*"
SLUG=$(printf '%s' "$DESC_RAW" |
    tr '[:upper:]' '[:lower:]' |
    tr ' -' '__' |
    tr -cd 'a-z0-9_' |
    sed -E 's/_+/_/g' |
    sed -E 's/^_|_$//g')
if [[ -z "$SLUG" ]]; then
    echo "ERROR: description slugified to empty string" >&2
    exit 2
fi

FILE="$DIR/${NEXT}_${SLUG}.sql"
if [[ -e "$FILE" ]]; then
    echo "ERROR: $FILE already exists" >&2
    exit 3
fi

cat >"$FILE" <<EOF
-- Migration ${NEXT}: ${DESC_RAW}
-- Created: $(date -u +%Y-%m-%dT%H:%M:%SZ)
--
-- Migrations are applied in numeric order on app boot (or via
-- RUN_MIGRATIONS_ONLY=1 ./tarassov_me). Use --verify-migrations to
-- list pending without applying.
--
-- The MigrationRunner already wraps this file in ONE transaction (under an
-- advisory lock) together with the schema_migrations bookkeeping. Do NOT add
-- BEGIN/COMMIT — an embedded COMMIT ends that transaction early and breaks
-- atomicity. Prefer idempotent DDL (IF NOT EXISTS / ON CONFLICT DO NOTHING).
EOF

if [[ -n "$TABLE" ]]; then
    # Active DDL for the new-resource.sh stub shape (id/name/created_at/updated_at).
    cat >>"$FILE" <<EOF

CREATE TABLE IF NOT EXISTS ${TABLE} (
    id         UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name       TEXT        NOT NULL,   -- TODO: replace with your real columns
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Bump updated_at on every UPDATE via the shared function from
-- migrations/000_updated_at_trigger.sql.
DROP TRIGGER IF EXISTS ${TABLE}_touch_updated_at ON ${TABLE};
CREATE TRIGGER ${TABLE}_touch_updated_at
    BEFORE UPDATE ON ${TABLE}
    FOR EACH ROW EXECUTE FUNCTION touch_updated_at();
EOF
else
    # Commented skeleton — copy/uncomment for the common table shape, or write
    # your own DDL. The trigger uses the shared touch_updated_at() function from
    # migrations/000_updated_at_trigger.sql.
    cat >>"$FILE" <<'EOF'

-- TODO: write your DDL here. Common table skeleton (uncomment + rename):
--
-- CREATE TABLE IF NOT EXISTS your_table (
--     id         UUID PRIMARY KEY DEFAULT gen_random_uuid(),
--     name       TEXT        NOT NULL,
--     created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
--     updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
-- );
--
-- DROP TRIGGER IF EXISTS your_table_touch_updated_at ON your_table;
-- CREATE TRIGGER your_table_touch_updated_at
--     BEFORE UPDATE ON your_table
--     FOR EACH ROW EXECUTE FUNCTION touch_updated_at();
EOF
fi

echo "==> Created $FILE"
