/**
 * @file test_post_domain.cpp
 * @brief Unit tests for Domain::Post (serialization). No infra — runs in
 *        the unit bucket. Generated by scripts/new-resource.sh.
 */

#include <gtest/gtest.h>

#include <nlohmann/json.hpp>

#include "domain/Post.hpp"

using json = nlohmann::json;

TEST(PostDomain, ToJsonSerializesEveryField) {
    Domain::Post e;
    e.id = "11111111-1111-1111-1111-111111111111";
    e.slug = "hello-world";
    e.title = "Hello, world";
    e.summary = "First post";
    e.body = "# Hello\n\nbody";
    e.status = "published";
    e.published_at = "2026-01-02T00:00:00Z";
    e.created_at = "2026-01-01T00:00:00Z";
    e.updated_at = "2026-01-01T00:00:00Z";

    json j = e;  // ADL to_json

    EXPECT_EQ(j["id"], e.id);
    EXPECT_EQ(j["slug"], e.slug);
    EXPECT_EQ(j["title"], e.title);
    EXPECT_EQ(j["summary"], e.summary);
    EXPECT_EQ(j["body"], e.body);
    EXPECT_EQ(j["status"], e.status);
    EXPECT_EQ(j["published_at"], *e.published_at);
    EXPECT_EQ(j["created_at"], e.created_at);
    EXPECT_EQ(j["updated_at"], e.updated_at);
}

TEST(PostDomain, ToJsonRendersNullPublishedAtForDrafts) {
    Domain::Post e;
    e.status = "draft";  // published_at left nullopt

    json j = e;

    EXPECT_TRUE(j["published_at"].is_null());
}
